spring.application.name=inventory-service

#servidor de configuración
spring.config.import=optional:configserver:http://localhost:8888

# Actuator: Le decimos que nos deje ver todos los "chequeos"
management.endpoints.web.exposure.include=*

# Dirección del servidor de descubrimiento (Eureka)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Forzar el registro inmediato (útil para pruebas)
eureka.instance.lease-renewal-interval-in-seconds=5

eureka.instance.hostname=localhost
eureka.instance.ip-address=127.0.0.1
eureka.instance.prefer-ip-address=true
# Esto asegura que lo local mande sobre el Config Server
spring.cloud.config.override-none=false
spring.cloud.config.allow-override=true

